Config:
  chatJoinLeaveAnnouncer: true
  ChatJoinMessage:
    Groups:
      admin: '&a[+] %vault_prefix% &r%player_name%'
      default: '&a[+] &fWelcome &r%player_name%'
  ChatLeaveMessage:
    Groups:
      admin: '&4[-] %vault_prefix% &f%player_name%'
      default: '&4[-] &f%player_name%'
  ChatFormat:
    Groups:
      admin: '&4&lAdmin &f{player} &8&l» &f{msg}'
      default: '{player} &8&l» &f{msg}'