name: zAngelChat
version: '${version}'
main: es.angelillo15.zangelchat.ZAngelChat
api-version: 1.16
authors: [ Angelillo15 ]
website: angelillo15.es
commands:
  zac:
    description: "Main Command of the plugin"
  msg:
    description: "Command to send msg"
    aliases: [tell, whisper, msg]